spring:
  datasource:
    url: jdbc:mysql://13.124.47.153:3306/scsprbasic2025?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ivill0080@
    driver-class-name: com.mysql.cj.jdbc.Driver